"""Display names (English and German) and extra languages for the language picker.

``config_language_data.SUPPORTED_LANGUAGES`` used to stop at 64 languages
while subtitle providers serve far more — the catalog providers alone declare
224 codes. ``EXTRA_LANGUAGES`` adds every remaining ISO 639-1 language
(``nb``/``nn`` fold into ``no`` and stay out). Each row is
``(code, iso639-3, iso639-2/B, English name, German name)``.
"""

from __future__ import annotations

GERMAN_NAMES: dict[str, str] = {
    "af": "Afrikaans",
    "sq": "Albanisch",
    "ar": "Arabisch",
    "hy": "Armenisch",
    "az": "Aserbaidschanisch",
    "eu": "Baskisch",
    "bn": "Bengalisch",
    "bs": "Bosnisch",
    "bg": "Bulgarisch",
    "ca": "Katalanisch",
    "zh": "Chinesisch",
    "zh-hans": "Chinesisch (vereinfacht)",
    "zh-hant": "Chinesisch (traditionell)",
    "hr": "Kroatisch",
    "cs": "Tschechisch",
    "da": "Dänisch",
    "nl": "Niederländisch",
    "en": "Englisch",
    "et": "Estnisch",
    "tl": "Filipino",
    "fi": "Finnisch",
    "fr": "Französisch",
    "gl": "Galicisch",
    "ka": "Georgisch",
    "de": "Deutsch",
    "el": "Griechisch",
    "he": "Hebräisch",
    "hi": "Hindi",
    "hu": "Ungarisch",
    "is": "Isländisch",
    "id": "Indonesisch",
    "it": "Italienisch",
    "ja": "Japanisch",
    "kn": "Kannada",
    "kk": "Kasachisch",
    "ko": "Koreanisch",
    "lv": "Lettisch",
    "lt": "Litauisch",
    "mk": "Mazedonisch",
    "ms": "Malaiisch",
    "ml": "Malayalam",
    "mn": "Mongolisch",
    "no": "Norwegisch",
    "fa": "Persisch",
    "pl": "Polnisch",
    "pt": "Portugiesisch",
    "ro": "Rumänisch",
    "ru": "Russisch",
    "sr": "Serbisch",
    "si": "Singhalesisch",
    "sk": "Slowakisch",
    "sl": "Slowenisch",
    "es": "Spanisch",
    "sw": "Swahili",
    "sv": "Schwedisch",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thailändisch",
    "tr": "Türkisch",
    "uk": "Ukrainisch",
    "ur": "Urdu",
    "uz": "Usbekisch",
    "vi": "Vietnamesisch",
}

EXTRA_LANGUAGES: list[tuple[str, str, str, str, str]] = [
    ("aa", "aar", "aar", "Afar", "Afar"),
    ("ab", "abk", "abk", "Abkhazian", "Abchasisch"),
    ("ae", "ave", "ave", "Avestan", "Avestisch"),
    ("ak", "aka", "aka", "Akan", "Akan"),
    ("am", "amh", "amh", "Amharic", "Amharisch"),
    ("an", "arg", "arg", "Aragonese", "Aragonesisch"),
    ("as", "asm", "asm", "Assamese", "Assamesisch"),
    ("av", "ava", "ava", "Avaric", "Awarisch"),
    ("ay", "aym", "aym", "Aymara", "Aymara"),
    ("ba", "bak", "bak", "Bashkir", "Baschkirisch"),
    ("be", "bel", "bel", "Belarusian", "Belarussisch"),
    ("bi", "bis", "bis", "Bislama", "Bislama"),
    ("bm", "bam", "bam", "Bambara", "Bambara"),
    ("bo", "bod", "tib", "Tibetan", "Tibetisch"),
    ("br", "bre", "bre", "Breton", "Bretonisch"),
    ("ce", "che", "che", "Chechen", "Tschetschenisch"),
    ("ch", "cha", "cha", "Chamorro", "Chamorro"),
    ("co", "cos", "cos", "Corsican", "Korsisch"),
    ("cr", "cre", "cre", "Cree", "Cree"),
    ("cu", "chu", "chu", "Church Slavonic", "Kirchenslawisch"),
    ("cv", "chv", "chv", "Chuvash", "Tschuwaschisch"),
    ("cy", "cym", "wel", "Welsh", "Walisisch"),
    ("dv", "div", "div", "Dhivehi", "Dhivehi"),
    ("dz", "dzo", "dzo", "Dzongkha", "Dzongkha"),
    ("ee", "ewe", "ewe", "Ewe", "Ewe"),
    ("eo", "epo", "epo", "Esperanto", "Esperanto"),
    ("ff", "ful", "ful", "Fula", "Fulfulde"),
    ("fj", "fij", "fij", "Fijian", "Fidschi"),
    ("fo", "fao", "fao", "Faroese", "Färöisch"),
    ("fy", "fry", "fry", "Western Frisian", "Westfriesisch"),
    ("ga", "gle", "gle", "Irish", "Irisch"),
    ("gd", "gla", "gla", "Scottish Gaelic", "Schottisch-Gälisch"),
    ("gn", "grn", "grn", "Guarani", "Guaraní"),
    ("gu", "guj", "guj", "Gujarati", "Gujarati"),
    ("gv", "glv", "glv", "Manx", "Manx"),
    ("ha", "hau", "hau", "Hausa", "Hausa"),
    ("ho", "hmo", "hmo", "Hiri Motu", "Hiri Motu"),
    ("ht", "hat", "hat", "Haitian Creole", "Haitianisch"),
    ("hz", "her", "her", "Herero", "Herero"),
    ("ia", "ina", "ina", "Interlingua", "Interlingua"),
    ("ie", "ile", "ile", "Interlingue", "Interlingue"),
    ("ig", "ibo", "ibo", "Igbo", "Igbo"),
    ("ii", "iii", "iii", "Sichuan Yi", "Sichuan-Yi"),
    ("ik", "ipk", "ipk", "Inupiaq", "Inupiaq"),
    ("io", "ido", "ido", "Ido", "Ido"),
    ("iu", "iku", "iku", "Inuktitut", "Inuktitut"),
    ("jv", "jav", "jav", "Javanese", "Javanisch"),
    ("kg", "kon", "kon", "Kongo", "Kikongo"),
    ("ki", "kik", "kik", "Kikuyu", "Kikuyu"),
    ("kj", "kua", "kua", "Kuanyama", "Kwanyama"),
    ("kl", "kal", "kal", "Greenlandic", "Grönländisch"),
    ("km", "khm", "khm", "Khmer", "Khmer"),
    ("kr", "kau", "kau", "Kanuri", "Kanuri"),
    ("ks", "kas", "kas", "Kashmiri", "Kaschmiri"),
    ("ku", "kur", "kur", "Kurdish", "Kurdisch"),
    ("kv", "kom", "kom", "Komi", "Komi"),
    ("kw", "cor", "cor", "Cornish", "Kornisch"),
    ("ky", "kir", "kir", "Kyrgyz", "Kirgisisch"),
    ("la", "lat", "lat", "Latin", "Latein"),
    ("lb", "ltz", "ltz", "Luxembourgish", "Luxemburgisch"),
    ("lg", "lug", "lug", "Ganda", "Luganda"),
    ("li", "lim", "lim", "Limburgish", "Limburgisch"),
    ("ln", "lin", "lin", "Lingala", "Lingala"),
    ("lo", "lao", "lao", "Lao", "Laotisch"),
    ("lu", "lub", "lub", "Luba-Katanga", "Kiluba"),
    ("mg", "mlg", "mlg", "Malagasy", "Malagasy"),
    ("mh", "mah", "mah", "Marshallese", "Marshallesisch"),
    ("mi", "mri", "mao", "Maori", "Maori"),
    ("mr", "mar", "mar", "Marathi", "Marathi"),
    ("mt", "mlt", "mlt", "Maltese", "Maltesisch"),
    ("my", "mya", "bur", "Burmese", "Birmanisch"),
    ("na", "nau", "nau", "Nauruan", "Nauruisch"),
    ("nd", "nde", "nde", "North Ndebele", "Nord-Ndebele"),
    ("ne", "nep", "nep", "Nepali", "Nepalesisch"),
    ("ng", "ndo", "ndo", "Ndonga", "Ndonga"),
    ("nr", "nbl", "nbl", "South Ndebele", "Süd-Ndebele"),
    ("nv", "nav", "nav", "Navajo", "Navajo"),
    ("ny", "nya", "nya", "Chichewa", "Chichewa"),
    ("oc", "oci", "oci", "Occitan", "Okzitanisch"),
    ("oj", "oji", "oji", "Ojibwe", "Ojibwe"),
    ("om", "orm", "orm", "Oromo", "Oromo"),
    ("or", "ori", "ori", "Odia", "Oriya"),
    ("os", "oss", "oss", "Ossetian", "Ossetisch"),
    ("pa", "pan", "pan", "Punjabi", "Panjabi"),
    ("pi", "pli", "pli", "Pali", "Pali"),
    ("ps", "pus", "pus", "Pashto", "Paschtu"),
    ("qu", "que", "que", "Quechua", "Quechua"),
    ("rm", "roh", "roh", "Romansh", "Rätoromanisch"),
    ("rn", "run", "run", "Kirundi", "Kirundi"),
    ("rw", "kin", "kin", "Kinyarwanda", "Kinyarwanda"),
    ("sa", "san", "san", "Sanskrit", "Sanskrit"),
    ("sc", "srd", "srd", "Sardinian", "Sardisch"),
    ("sd", "snd", "snd", "Sindhi", "Sindhi"),
    ("se", "sme", "sme", "Northern Sami", "Nordsamisch"),
    ("sg", "sag", "sag", "Sango", "Sango"),
    ("sm", "smo", "smo", "Samoan", "Samoanisch"),
    ("sn", "sna", "sna", "Shona", "Shona"),
    ("so", "som", "som", "Somali", "Somali"),
    ("ss", "ssw", "ssw", "Swati", "Siswati"),
    ("st", "sot", "sot", "Southern Sotho", "Süd-Sotho"),
    ("su", "sun", "sun", "Sundanese", "Sundanesisch"),
    ("tg", "tgk", "tgk", "Tajik", "Tadschikisch"),
    ("ti", "tir", "tir", "Tigrinya", "Tigrinya"),
    ("tk", "tuk", "tuk", "Turkmen", "Turkmenisch"),
    ("tn", "tsn", "tsn", "Tswana", "Setswana"),
    ("to", "ton", "ton", "Tongan", "Tongaisch"),
    ("ts", "tso", "tso", "Tsonga", "Xitsonga"),
    ("tt", "tat", "tat", "Tatar", "Tatarisch"),
    ("tw", "twi", "twi", "Twi", "Twi"),
    ("ty", "tah", "tah", "Tahitian", "Tahitianisch"),
    ("ug", "uig", "uig", "Uyghur", "Uigurisch"),
    ("ve", "ven", "ven", "Venda", "Tshivenda"),
    ("vo", "vol", "vol", "Volapük", "Volapük"),
    ("wa", "wln", "wln", "Walloon", "Wallonisch"),
    ("wo", "wol", "wol", "Wolof", "Wolof"),
    ("xh", "xho", "xho", "Xhosa", "isiXhosa"),
    ("yi", "yid", "yid", "Yiddish", "Jiddisch"),
    ("yo", "yor", "yor", "Yoruba", "Yoruba"),
    ("za", "zha", "zha", "Zhuang", "Zhuang"),
    ("zu", "zul", "zul", "Zulu", "isiZulu"),
]
