"""Reusable Pydantic models registered as OpenAPI ``components/schemas``.

Every model here gets surfaced in the spec under
``#/components/schemas/<ClassName>`` so route YAML can use
``schema: { $ref: '#/components/schemas/...' }`` instead of inlining the
shape. The same models are the foundation for upcoming request-validation
decorators (Pydantic-driven 422 responses) and frontend codegen via Orval.

Add new components by:
1. Defining a ``pydantic.BaseModel`` subclass below.
2. Listing the class in ``REGISTERED_COMPONENTS`` at the bottom.

The registration loop in ``openapi.register_all_paths`` calls
``spec.components.schema(name, schema=Model.model_json_schema())`` for
each entry, so the JSON-Schema generated by Pydantic v2 is what the
``/api/v1/openapi.json`` endpoint serves.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ErrorResponse(BaseModel):
    """Standard error envelope for 4xx/5xx responses.

    Every route's failure path returns this shape. Routes can extend the
    ``details`` field with structured per-error context (e.g. validation
    field paths, retry timestamps) without breaking the contract.
    """

    model_config = ConfigDict(json_schema_extra={"example": {"error": "Item not found"}})

    error: str = Field(description="Human-readable error summary")
    details: dict | None = Field(
        default=None,
        description="Optional structured context (validation errors, retry info, etc.)",
    )


class WantedItem(BaseModel):
    """A subtitle download target tracked in the wanted_items table."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": 12345,
                "title": "My Show — S01E02 [DE]",
                "file_path": "/media/show/s01/ep02.mkv",
                "item_type": "episode",
                "target_language": "de",
                "missing_languages": ["de"],
                "status": "wanted",
                "priority": "standard",
                "current_score": 0,
                "search_count": 1,
            }
        }
    )

    id: int
    title: str
    file_path: str = Field(description="Absolute path to the parent video container")
    item_type: str = Field(description="One of: episode, movie")
    target_language: str = Field(description="Primary missing language (BCP-47-ish)")
    missing_languages: list[str] = Field(default_factory=list)
    status: str = Field(description="One of: wanted, found, extracted, failed, paused")
    priority: str = Field(default="standard", description="One of: low, standard, high")
    current_score: int = 0
    search_count: int = 0
    error: str = ""
    error_count: int = 0
    embedded_languages: list[str] = Field(default_factory=list)
    existing_sub: str = ""
    sonarr_episode_id: int | None = None
    sonarr_series_id: int | None = None
    radarr_movie_id: int | None = None
    standalone_movie_id: int | None = None
    standalone_series_id: int | None = None
    instance_name: str | None = None
    added_at: str | None = None
    updated_at: str | None = None
    last_search_at: str | None = None


class LanguageProfile(BaseModel):
    """A user-defined language profile that drives extract/search/cleanup decisions."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": 1,
                "name": "Standard",
                "source_language": "en",
                "target_languages": ["de", "en"],
                "is_default": True,
                "translation_backend": None,
            }
        }
    )

    id: int
    name: str
    source_language: str
    target_languages: list[str]
    target_language_names: list[str] | None = None
    is_default: bool = False
    translation_backend: str | None = None
    fallback_chain: list[str] | None = None
    forced_preference: str | None = None
    must_contain: list[str] = Field(default_factory=list)
    must_not_contain: list[str] = Field(default_factory=list)
    cutoff_language: str = ""
    audio_exclude_languages: list[str] = Field(default_factory=list)
    hi_preference: str = "include"
    forced_scoring: str = "include"


class CleanupRule(BaseModel):
    """Scheduler-driven cleanup rule (orphan/duplicate/age/format/lang)."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": 7,
                "name": "Purge orphan .bak older than 30d",
                "rule_type": "old_subtitle_baks",
                "enabled": True,
                "threshold_days": 30,
                "last_run_at": "2026-05-01T15:30:00Z",
            }
        }
    )

    id: int
    name: str
    rule_type: str = Field(
        description=(
            "One of: language_filter, format_upgrade, orphan_files, orphan_db, "
            "old_subtitle_baks, old_backups, dedup, orphaned, foreign_tracks, "
            "signs_cleanup"
        )
    )
    enabled: bool = True
    threshold_days: int | None = None
    threshold_score: int | None = None
    target_format: str | None = None
    target_languages: list[str] | None = None
    auto_run: bool = False
    last_run_at: str | None = None


class SubtitleSidecar(BaseModel):
    """A subtitle file living next to a video container."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "path": "/media/show/s01/ep02.de.srt",
                "language": "de",
                "format": "srt",
                "modifier": None,
                "size_bytes": 12873,
            }
        }
    )

    path: str
    language: str
    format: str = Field(description="One of: srt, ass, vtt")
    modifier: str | None = Field(
        default=None,
        description="Optional sidecar modifier: hi | forced | sdh | cc | None for primary",
    )
    size_bytes: int | None = None
    score: int | None = None
    is_backup: bool = Field(default=False, description="True for .bak.<ext> backup files")


# Order matters — components emitted into the spec in this order so
# `$ref` consumers can rely on stable component IDs.
REGISTERED_COMPONENTS: list[type[BaseModel]] = [
    ErrorResponse,
    WantedItem,
    LanguageProfile,
    CleanupRule,
    SubtitleSidecar,
]
